import {
	AccessTimeFilled,
	BedroomChild,
	Bloodtype,
	BlurOn,
	CalendarMonth,
	DateRange,
	Deblur,
	Email,
	HealthAndSafety,
	History,
	Info,
	LocalPhone,
	LocationCity,
	Map,
	MonitorHeart,
	Person,
	Person2,
	Shield,
	Sick,
	SwapHoriz,
	Wc,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddBedAllotmentSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "allotedDate",
		label: "Alloted Date *",
		placeholder: "Enter Alloted Date",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "date",
		validationSchema: Yup.string().required("Alloted Date required"),
		initialValue: "",
		icon: <CalendarMonth />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	// {
	// 	key: "2",
	// 	// placeholder: 'Enter your name',
	// 	name: "Lname",
	// 	label: "Last Name *",
	// 	placeholder: "Last Name",
	// 	styleContact: "rounded-xl overflow-hidden bg-white ",
	// 	type: "text",
	// 	validationSchema: Yup.string()
	// 		.required("Last Name required")
	// 		.min(2, "Last Name must be at least 2 characters"),
	// 	initialValue: "",
	// 	icon: <Person />,
	// 	required: true,
	// 	contactField: {
	// 		xs: 12,
	// 		sm: 12,
	// 		md: 6,
	// 		lg: 6,
	// 	},
	// },
	{
		key: "2",
		name: "allotedTime",
		label: "Alloted Time *",
		placeholder: "Enter Alloted Time",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Alloted Time Required"),
		type: "time",
		initialValue: "",
		icon: <AccessTimeFilled />,
		required: true,
	},
	{
		key: "3",
		name: "bedCategory",
		label: "Bed Category *",
		placeholder: "Select Bed Category",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Bed Category is required"),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "4",
		// placeholder: 'Enter your email',
		name: "id",
		label: "Bed Id ",
		placeholder: "Enter Bed Id",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Bed Id required"),
		initialValue: "",
		icon: <BedroomChild />,
		required: true,
	},
	{
		key: "5",
		name: "patient",
		label: "Patient *",
		placeholder: "Select Patient",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select blood group"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "6",
		name: "category",
		label: "Category *",
		placeholder: "Select Category",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Category"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "7",
		// placeholder: 'Enter your phone number',
		name: "reactions",
		label: "Reactions *",
		placeholder: "Reactions",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Reactions required"),
		initialValue: "",
		icon: <Deblur />,
		required: true,
	},
	{
		key: "8",
		name: "transfererFrom",
		label: "Transferred From *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		type: "text",
		initialValue: "",
		placeholder: "Transferred From",
		icon: <SwapHoriz />,
		required: true,
	},

	{
		key: "17",
		name: "clinic",
		label: "Clinic *",
		placeholder: "Select Clinic",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Clinic"),
		initialValue: "",
		icon: <Wc />,
		required: true,
	},
	{
		key: "18",
		name: "doctor",
		label: "Doctor",
		placeholder: "Select Doctor",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Doctor"),
		initialValue: "",
		icon: <Wc />,
		required: true,
	},
	{
		key: "9",
		name: "diagnosis",
		label: "Diagnosis *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		type: "text",
		initialValue: "",
		placeholder: "Diagnosis And Hospitalization",
		icon: <MonitorHeart />,
		required: true,
	},
	{
		key: "10",
		name: "otherIllnesses",
		label: "Other Illnesses *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		type: "text",
		initialValue: "",
		placeholder: "Other Illnesses",
		icon: <Sick />,
		required: true,
	},
	{
		key: "11",
		name: "history",
		label: "History *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		type: "text",
		initialValue: "",
		placeholder: "History",
		icon: <History />,
		required: true,
	},
	{
		key: "12",
		name: "bloodGroup",
		label: "Blood Group *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		initialValue: "",
		type: "text",
		placeholder: "Blood Group",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "12",
		name: "referredDoctor ",
		label: "Referred Doctor  *",
		validationSchema: Yup.string().required("Details required"),
		styleContact: "rounded-lg",
		type: "text",
		initialValue: "",
		placeholder: "Referred Doctor",
		icon: <Person2 />,
		required: true,
	},

	// {
	// 	key: "9",
	// 	name: "postalCode",
	// 	type: "text",
	// 	placeholder: "Postal Code",
	// 	styleContact: "rounded-lg",
	// 	label: "Postal Code*",
	// 	validationSchema: Yup.string().required("Postal Code is required"),
	// 	initialValue: "",
	// 	icon: <PushPin />,
	// 	required: true,
	// },
];
export default AddBedAllotmentSchemas;
