import {
	CurrencyRupee,
	Info,
	Inventory,
	Person,
	Workspaces,
	DriveFileRenameOutline,
	Business,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddMedichineSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "name",
		label: "Name *",
		placeholder: "Enter Medicine name",
		styleContact: "rounded-xl bg-white ",
		type: "text",
		validationSchema: Yup.string().required("Medicine name is required"),
		initialValue: "",
		icon: <Person />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "category",
		label: "Category *",
		placeholder: "Select Category",
		styleContact: "rounded-xl bg-white ",
		validationSchema: Yup.string().required("Category is required"),
		initialValue: "",
		icon: <Person />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "3",
		name: "storeBox",
		label: "Store Box *",
		type: "text",
		placeholder: "Enter Store Box",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Details required"),

		initialValue: "",
		icon: <Inventory />,
		required: true,
	},
	{
		key: "4",
		name: "purchasePrice",
		label: "Purchase Price *",
		placeholder: "Enter Purchase Price",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Purchase Price Required"),
		type: "number",
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
	{
		key: "5",
		// placeholder: 'Enter your email',
		name: "sellPrice",
		label: "Sell Price *",
		placeholder: "Enter Sell Price",
		styleContact: "rounded-lg",
		type: "number",
		validationSchema: Yup.string().required("Sell Price is required"),
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
	{
		key: "6",
		// placeholder: 'Enter your phone number',
		name: "qty",
		label: "Qty *",
		placeholder: "Enter Qty",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Qty is required"),
		initialValue: "",
		icon: <Workspaces />,
		required: true,
	},
	{
		key: "7",
		name: "genericName",
		label: "Generic Name *",
		validationSchema: Yup.string().required("Generic Name is required"),
		type: "text",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		icon: <DriveFileRenameOutline />,
		required: true,
	},
	{
		key: "8",
		name: "company",
		label: "Company *",
		validationSchema: Yup.string().required("Generic Name is required"),
		type: "text",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		icon: <Business />,
		required: true,
	},
	{
		key: "9",
		name: "effects",
		label: "Effects *",
		validationSchema: Yup.string().required("Details Required"),
		type: "text",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		icon: <Business />,
		required: true,
	},
	{
		key: "10",
		name: "expire",
		label: "Expire Date *",
		validationSchema: Yup.string().required("Expire Date is required"),
		type: "date",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		icon: <Business />,
		required: true,
	},
	{
		key: "11",
		name: "description",
		label: "Description *",
		validationSchema: Yup.string().optional(),
		type: "text",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		required: true,
		// multiline: true,
		// rows: 2,
		icon: <Info />,
	},
];
export default AddMedichineSchemas;
