import {
	Category,
	CurrencyRupee,
	Dns,
	Group,
	Info,
	Inventory,
	LocationCity,
	Person,
	SpaceBar,
	VaccinesSharp,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddNewProductSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your phone number',
		name: "name",
		label: "Name *",
		placeholder: "Name",
		styleContact: "rounded-lg",
		// type: "text",
		validationSchema: Yup.string().required("Name is required"),
		initialValue: "",
		icon: <Person />,
		required: true,
	},
	{
		key: "2",
		// placeholder: 'Enter your phone number',
		name: "city",
		label: "City *",
		placeholder: "ContactNumber",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("contact number is required"),
		initialValue: "",
		icon: <LocationCity />,
		required: true,
	},

	{
		key: "3",
		name: "space",
		label: "Space Availability *",
		validationSchema: Yup.string().optional(),
		type: "number",
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		multiline: true,
		required: true,
		icon: <Group />,
	},
	// {
	// 	key: "4",
	// 	name: "stock",
	// 	label: "Stock *",
	// 	validationSchema: Yup.string().optional(),
	// 	type: "number",
	// 	styleContact: "rounded-lg",
	// 	initialValue: "",
	// 	placeholder: "",
	// 	required: true,
	// 	icon: <Inventory />,
	// },
	// {
	// 	key: "5",
	// 	name: "description",
	// 	label: "Description ",
	// 	validationSchema: Yup.string().optional(),
	// 	type: "text",
	// 	styleContact: "rounded-lg",
	// 	initialValue: "",
	// 	placeholder: "",
	// 	required: true,
	// 	multiline: true,
	// 	rows: 2,
	// 	icon: <Info />,
	// },

	// {
	// 	key: "6",
	// 	name: "photo",
	// 	label: "Gender",
	// 	placeholder: "Select Gender",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Select Gender"),
	// 	initialValue: "",
	// 	icon: <Wc />,
	// 	required: true,
	// },
];
export default AddNewProductSchemas;
