import {
	ContactPhone,
	Info,
	LocalPhone,
	LocationCity,
	Map,
	PushPin,
	Room,
	WaterDamage,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddNewClinicSchema = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "clinicName",
		label: "Clinic Name *",
		placeholder: "Enter Clinic Name",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "text",
		validationSchema: Yup.string()
			.required("Clinic Name required")
			.min(2, "Clinic Name must be at least 2 characters"),
		initialValue: "",
		icon: <WaterDamage />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},

	{
		key: "2",
		// placeholder: 'Enter your phone number',
		name: "phoneNumber",
		label: "Contact Number *",
		placeholder: "ContactNumber",
		styleContact: "rounded-lg",
		type: "number",
		validationSchema: Yup.string().required("Contact number is required"),
		initialValue: "",
		icon: <ContactPhone />,
		required: true,
	},

	{
		key: "3",
		name: "city",
		label: "City *",
		validationSchema: Yup.string().required("City is required"),
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "City",
		icon: <LocationCity />,
		required: true,
	},

	{
		key: "4",
		name: "countryCode",
		label: "countryDetails",
		placeholder: "Country Code",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().optional(),
		initialValue: "",
		icon: <LocalPhone />,
		required: true,
	},

	{
		key: "5",
		name: "address",
		label: "Address*",
		placeholder: "About",
		type: "text",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string()
			.required("Address is required")
			.min(8, "Address must be greater than 8 characters"),

		initialValue: "",
		icon: <Room />,
		required: true,
		multiline: true,
		rows: 2,
	},

	{
		key: "6",
		name: "postalCode",
		type: "text",
		placeholder: "Postal Code",
		styleContact: "rounded-lg",
		label: "Postal Code*",
		validationSchema: Yup.string().required("Postal Code is required"),
		initialValue: "",
		icon: <PushPin />,
		required: true,
	},
	{
		key: "7",
		name: "mapLink",
		label: "Map Link *",
		placeholder: "Enter map link",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Map Link is required"),
		icon: <Map />,
		initialValue: "",
		required: true,
	},
	{
		key: "8",
		name: "about",
		label: "About *",
		placeholder: "About",
		type: "text",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string()
			.required("Description is required")
			.min(11, "Description must be greater than 11 characters"),

		initialValue: "",
		icon: <Info />,
		required: true,
		multiline: true,
		rows: 2,
	},
	// {
	// 	key: "10.2",
	// 	name: "state",
	// 	type: "text",
	// 	placeholder: "State",
	// 	styleContact: "rounded-lg",
	// 	label: "State",
	// 	validationSchema: Yup.string().optional(),
	// 	initialValue: "",
	// 	icon: <AccessAlarm />,
	// 	required: true,
	// },
	// {
	// 	key: "10",
	// 	name: "latitude",
	// 	type: "text",
	// 	placeholder: "Latitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Latitude*",
	// 	validationSchema: Yup.string().required("Latitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
	// {
	// 	key: "11",
	// 	name: "longitude",
	// 	type: "text",
	// 	placeholder: "Longitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Longitude*",
	// 	validationSchema: Yup.string().required("Longitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
];
export default AddNewClinicSchema;
