import {
	Category,
	Create,
	Info,
	Badge,
	Description,
	CurrencyRupee,
	Percent,
	CalendarMonth,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddPaymentSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "id",
		label: "Invoice Id *",
		placeholder: "Enter invoice id",
		styleContact: "rounded-xl overflow-hidden bg-white",
		type: "text",
		validationSchema: Yup.string().required("Invoice Id Required"),
		initialValue: "",
		icon: <Create />,
		required: true,
	},
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "clinic",
		label: "Enter Clinic Name *",
		placeholder: "Enter clinic name",
		styleContact: "rounded-xl overflow-hidden bg-white",
		validationSchema: Yup.string().required("Clinic name required"),
		initialValue: "",
		icon: <Badge />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "3",
		// placeholder: 'Enter your name',
		name: "doctor",
		label: "Refd By Doctor *",
		placeholder: "Enter Doctor name",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Doctor name is Required"),
		initialValue: "",
		icon: <Description />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "4",
		// placeholder: 'Enter your name',
		name: "date",
		label: "Select Date *",
		placeholder: "Select Date",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Date is required"),
		type: "date",
		initialValue: "",
		icon: <CalendarMonth />,
		required: true,
	},
	{
		key: "5",
		// placeholder: 'Enter your name',
		name: "subtotal",
		label: "Sub Total *",
		placeholder: "Enter Sub Total",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Sub Total price is required"),
		type: "number",
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
	{
		key: "6",
		// placeholder: 'Enter your name',
		name: "discount",
		label: "Discount *",
		placeholder: "Enter Discount",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Discount is required"),
		type: "number",
		initialValue: "",
		icon: <Percent />,
		required: true,
	},
	{
		key: "7",
		// placeholder: 'Enter your name',
		name: "grossTotal",
		label: "Gross Total *",
		placeholder: "Gross Total *",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Gross Total is required"),
		type: "number",
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
	{
		key: "8",
		// placeholder: 'Enter your name',
		name: "note",
		label: "Note *",
		placeholder: "Enter Type",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Type is required"),
		type: "text",
		initialValue: "",
		icon: <Create />,
		required: true,
	},
	{
		key: "9",
		// placeholder: 'Enter your name',
		name: "amount",
		label: "Deposited Amount *",
		placeholder: "Enter Type",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Type is required"),
		type: "number",
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
];
export default AddPaymentSchemas;
