import {
	Email,
	HealthAndSafety,
	LocalPhone,
	LocationCity,
	Person,
} from "@mui/icons-material";
import * as Yup from "yup";

const AddPharmacySaleSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "invoiceId",
		label: "Invoice Id *",
		placeholder: "Enter Invoice Id",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "text",
		validationSchema: Yup.string().required("Invoice Id is required"),
		initialValue: "",
		icon: <Person />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "itemName",
		label: "Item Name *",
		placeholder: "Enter Item Name",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "text",
		validationSchema: Yup.string().required("Item name required"),
		initialValue: "",
		icon: <Person />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "3",
		name: "date",
		label: "Date *",
		type: "date",
		placeholder: "Enter Date",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Date"),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "4",
		name: "qty",
		label: "Qty *",
		placeholder: "Enter Qty",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Qty required"),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "5",
		// placeholder: 'Enter your email',
		name: "subTotal",
		label: "Sub Total *",
		placeholder: "Enter Sub Total",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Sub Total is required"),
		initialValue: "",
		icon: <Email />,
		required: true,
	},
	{
		key: "6",
		// placeholder: 'Enter your phone number',
		name: "discount",
		label: "Discount *",
		placeholder: "Enter Discount",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Discount is required"),
		initialValue: "",
		icon: <LocalPhone />,
		required: true,
	},
	{
		key: "7",
		name: "grandTotal",
		label: "Total Amount *",
		validationSchema: Yup.string().required("Total amount is required"),
		styleContact: "rounded-lg",
		initialValue: "",
		placeholder: "",
		icon: <LocationCity />,
		required: true,
	},
	// {
	// 	key: "4",
	// 	// placeholder: 'Enter your email',
	// 	name: "date",
	// 	label: "Date Of Birth *",
	// 	placeholder: "Enter Date Of Birth",
	// 	styleContact: "rounded-lg",
	// 	type: "date",
	// 	validationSchema: Yup.string().required("Date is required"),
	// 	initialValue: "",
	// 	icon: <DateRange />,
	// 	required: true,
	// },
	// {
	// 	key: "5",
	// 	name: "bloodGroup",
	// 	label: "Blood Group",
	// 	placeholder: "Select blood group",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Select blood group"),
	// 	initialValue: "",
	// 	icon: <Bloodtype />,
	// 	required: true,
	// },
	// {
	// 	key: "6",
	// 	name: "gender",
	// 	label: "Gender",
	// 	placeholder: "Select Gender",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Select Gender"),
	// 	initialValue: "",
	// 	icon: <Wc />,
	// 	required: true,
	// },

	// {
	// 	key: "9",
	// 	name: "postalCode",
	// 	type: "text",
	// 	placeholder: "Postal Code",
	// 	styleContact: "rounded-lg",
	// 	label: "Postal Code*",
	// 	validationSchema: Yup.string().required("Postal Code is required"),
	// 	initialValue: "",
	// 	icon: <PushPin />,
	// 	required: true,
	// },
	// {
	// 	key: "4",
	// 	name: "countryCode",
	// 	label: "countryDetails",
	// 	placeholder: "Country Code",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Select country"),
	// 	initialValue: "",
	// 	icon: <LocalPhone />,
	// 	required: true,
	// },
	// {
	// 	key: "10",
	// 	name: "address",
	// 	label: "Address*",
	// 	placeholder: "Address",
	// 	type: "text",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string()
	// 		.required("Address is required")
	// 		.min(11, "Address must be greater than 11 characters"),

	// 	initialValue: "",
	// 	icon: <Map />,
	// 	required: true,
	// 	multiline: true,
	// 	rows: 2,
	// },
	// {
	// 	key: "11",
	// 	name: "details",
	// 	label: "Details*",
	// 	placeholder: "Details",
	// 	type: "text",
	// 	// styleContact: "rounded-lg",
	// 	validationSchema: Yup.string()
	// 		.required("Description is required")
	// 		.min(11, "Description must be greater than 11 characters"),

	// 	initialValue: "",
	// 	icon: <Info />,
	// 	required: true,
	// 	multiline: true,
	// 	rows: 2,
	// },
];
export default AddPharmacySaleSchemas;
