import {
	AccessTimeFilled,
	BedroomChild,
	Bloodtype,
	BlurOn,
	CalendarMonth,
	DateRange,
	Deblur,
	Email,
	HealthAndSafety,
	History,
	Info,
	LocalPhone,
	LocationCity,
	Map,
	MonitorHeart,
	Person,
	Person2,
	Shield,
	Sick,
	SwapHoriz,
	Wc,
} from "@mui/icons-material";
import * as Yup from "yup";

const AllotmentServiceSchema = [
	{
		key: "1",
		name: "service",
		label: "Service *",
		placeholder: "Enter service name",
		type: "text",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("service name required"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "date",
		label: "Date *",
		placeholder: "Enter Date",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "date",
		validationSchema: Yup.string().required("Date required"),
		initialValue: "",
		icon: <CalendarMonth />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "3",
		name: "nurse",
		label: "Nurse *",
		placeholder: "Select Nurse",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Nurse"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "4",
		name: "qty",
		label: "Quantity *",
		placeholder: "Enter Qty",
		type: "number",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Enter Qty"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "5",
		name: "price",
		label: "Total Price *",
		placeholder: "Enter Price",
		type: "number",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Enter Price"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},

	// {
	// 	key: "2",
	// 	// placeholder: 'Enter your name',
	// 	name: "Lname",
	// 	label: "Last Name *",
	// 	placeholder: "Last Name",
	// 	styleContact: "rounded-xl overflow-hidden bg-white ",
	// 	type: "text",
	// 	validationSchema: Yup.string()
	// 		.required("Last Name required")
	// 		.min(2, "Last Name must be at least 2 characters"),
	// 	initialValue: "",
	// 	icon: <Person />,
	// 	required: true,
	// 	contactField: {
	// 		xs: 12,
	// 		sm: 12,
	// 		md: 6,
	// 		lg: 6,
	// 	},
	// },
];
export default AllotmentServiceSchema;
