import { BorderColor, NoteAlt } from "@mui/icons-material";
import * as Yup from "yup";

const DiagnosisSchemas = [
	// {
	// 	key: "1",
	// 	name: "selectPatient",
	// 	label: "Select Patient",
	// 	placeholder: "Select Patient",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Select Patient"),
	// 	initialValue: "",
	// 	required: true,
	// },

	// {
	// 	key: "5",
	// 	// placeholder: 'Enter your phone number',
	// 	name: "name",
	// 	label: "Name of the Lab Test *",
	// 	placeholder: "Enter Lab Test Name",
	// 	styleContact: "rounded-lg",
	// 	type: "text",
	// 	validationSchema: Yup.string().required("Lab Test Name is required"),
	// 	initialValue: "",
	// 	icon: <BorderColor />,
	// 	required: true,
	// },
	{
		key: "2",
		name: "name",
		label: "Diagnosis Name *",
		placeholder: "Enter Diagnosis Name",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Diagnosis name is required"),
		initialValue: "",
		icon: <BorderColor />,
		required: true,
	},

	{
		key: "3",
		name: "comment",
		label: "Additional Comments",
		placeholder: "Enter Diagnosis Notes",
		type: "text",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string().optional(),
		initialValue: "",
		required: true,
		icon: <NoteAlt />,
		multiline: true,
		rows: 2,
	},

	// {
	// 	key: "14",
	// 	name: "countryCode",
	// 	label: "countryDetails",
	// 	placeholder: "Country Code",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().optional(),

	// 	initialValue: "",
	// 	icon: <LocalPhone />,
	// 	required: true,
	// },

	// {
	// 	key: "6",
	// 	name: "city",
	// 	label: "City *",
	// 	validationSchema: Yup.string().required("City is required"),
	// 	styleContact: "rounded-lg",
	// 	initialValue: "",
	// 	placeholder: "City",
	// 	icon: <LocationCity />,
	// 	required: true,
	// },
	// {
	// 	key: "8",
	// 	name: "street",
	// 	label: "Street *",
	// 	placeholder: "Street",

	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Street is required"),
	// 	icon: <Traffic />,
	// 	initialValue: "",
	// 	required: true,
	// },
	// {
	// 	key: "9",
	// 	name: "zipCode",
	// 	type: "text",
	// 	placeholder: "ZipCode",
	// 	styleContact: "rounded-lg",
	// 	label: "ZipCode*",
	// 	validationSchema: Yup.string().required("ZipCode is required"),
	// 	initialValue: "",
	// 	icon: <PushPin />,
	// 	required: true,
	// },
	// {
	// 	key: "10.2",
	// 	name: "state",
	// 	type: "text",
	// 	placeholder: "State",
	// 	styleContact: "rounded-lg",
	// 	label: "State",
	// 	validationSchema: Yup.string().optional(),
	// 	initialValue: "",
	// 	icon: <AccessAlarm />,
	// 	required: true,
	// },
	// {
	// 	key: "10",
	// 	name: "latitude",
	// 	type: "text",
	// 	placeholder: "Latitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Latitude*",
	// 	validationSchema: Yup.string().required("Latitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
	// {
	// 	key: "11",
	// 	name: "longitude",
	// 	type: "text",
	// 	placeholder: "Longitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Longitude*",
	// 	validationSchema: Yup.string().required("Longitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
	// {
	// 	key: "11",
	// 	name: "timing",
	// 	type: "text",
	// 	placeholder: "Store Timing",
	// 	styleContact: "rounded-lg",
	// 	label: "Store Opening Hours*",
	// 	validationSchema: Yup.string().required("Store Timing is required"),
	// 	initialValue: "",
	// 	row: 2,
	// 	multiline: true,
	// 	// icon: <AddLocationAlt />,
	// 	required: true,
	// },
];
export default DiagnosisSchemas;
