import {
	AccessTimeFilled,
	AddModerator,
	BedroomChild,
	Bloodtype,
	BlurOn,
	CalendarMonth,
	DateRange,
	Deblur,
	Edit,
	Email,
	HealthAndSafety,
	History,
	Info,
	LocalPhone,
	LocationCity,
	Map,
	MedicationLiquid,
	MonitorHeart,
	Person,
	Person2,
	PointOfSale,
	Shield,
	Sick,
	SwapHoriz,
	Wc,
} from "@mui/icons-material";
import * as Yup from "yup";

const DischargeSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "checkOutDate",
		label: "Checkout Date *",
		placeholder: "Enter Checkout Date",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "date",
		validationSchema: Yup.string().required("Checkout Date is required"),
		initialValue: "",
		icon: <CalendarMonth />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	// {
	// 	key: "2",
	// 	// placeholder: 'Enter your name',
	// 	name: "Lname",
	// 	label: "Last Name *",
	// 	placeholder: "Last Name",
	// 	styleContact: "rounded-xl overflow-hidden bg-white ",
	// 	type: "text",
	// 	validationSchema: Yup.string()
	// 		.required("Last Name required")
	// 		.min(2, "Last Name must be at least 2 characters"),
	// 	initialValue: "",
	// 	icon: <Person />,
	// 	required: true,
	// 	contactField: {
	// 		xs: 12,
	// 		sm: 12,
	// 		md: 6,
	// 		lg: 6,
	// 	},
	// },
	{
		key: "2",
		name: "checkoutTime",
		label: "Checkout Time *",
		placeholder: "Enter Checkout Time",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Checkout Time is Required"),
		type: "time",
		initialValue: "",
		icon: <AccessTimeFilled />,
		required: true,
	},
	{
		key: "3",
		name: "finalDiagnosis",
		label: "Final Diagnosis *",
		placeholder: "Enter Final Diagnosis Details",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required(
			"Final Diagnosis Details is required"
		),

		initialValue: "",
		icon: <HealthAndSafety />,
		required: true,
	},
	// {
	// 	key: "4",
	// 	// placeholder: 'Enter your email',
	// 	name: "anatomopatologicDiagnosis:",
	// 	label: "Anatomopatologic Diagnosis *",
	// 	placeholder: "Enter Anatomopatologic Diagnosis Details",
	// 	styleContact: "rounded-lg",
	// 	type: "text",
	// 	validationSchema: Yup.string().required(
	// 		"Anatomopatologic Diagnosis is required"
	// 	),
	// 	initialValue: "",
	// 	icon: <BedroomChild />,
	// 	required: true,
	// },
	{
		key: "5",
		name: "checkoutDiagnosis",
		label: "Checkout Diagnosis: *",
		placeholder: "Enter Checkout Diagnosis",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required(
			"Checkout Diagnosis Details is required"
		),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "6",
		name: "checkoutState",
		label: "Checkout State *",
		placeholder: "Enter Checkout State",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Checkout State is required"),
		initialValue: "",
		icon: <PointOfSale />,
		required: true,
	},
	{
		key: "7",
		// placeholder: 'Enter your phone number',
		name: "initialState",
		label: "Initial State *",
		placeholder: "Enter Initial State",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Initial State is required"),
		initialValue: "",
		icon: <AddModerator />,
		required: true,
	},
	{
		key: "8",
		name: "finalDiagnosis",
		label: "Final Diagnosis *",
		placeholder: "Enter Final Diagnosis",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Final Diagnosis is required"),
		initialValue: "",
		icon: <MonitorHeart />,
		required: true,
	},

	{
		key: "17",
		name: "medicineAfterDischarge",
		label: "Medicine to take after Discharge *",
		placeholder: "Enter details",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Details Required"),
		initialValue: "",
		icon: <MedicationLiquid />,
		multiline: true,
		rows: 2,
		required: true,
	},
	{
		key: "17",
		name: "instructions",
		label: "Instructions *",
		placeholder: "Enter Instructions",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Instruction Required"),
		initialValue: "",
		icon: <Edit />,
		multiline: true,
		rows: 2,
		required: true,
	},
	{
		key: "18",
		name: "doctor",
		label: "Doctor",
		placeholder: "Select Doctor",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Doctor"),
		initialValue: "",
		icon: <Wc />,
		required: true,
	},
];
export default DischargeSchemas;
