import {
	AccessTimeFilled,
	Bloodtype,
	CalendarMonth,
	Info,
} from "@mui/icons-material";
import * as Yup from "yup";

const MedicineSchemas = [
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "date",
		label: "Date *",
		placeholder: "Enter Date",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		type: "date",
		validationSchema: Yup.string().required("Date required"),
		initialValue: "",
		icon: <CalendarMonth />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	// {
	// 	key: "2",
	// 	// placeholder: 'Enter your name',
	// 	name: "Lname",
	// 	label: "Last Name *",
	// 	placeholder: "Last Name",
	// 	styleContact: "rounded-xl overflow-hidden bg-white ",
	// 	type: "text",
	// 	validationSchema: Yup.string()
	// 		.required("Last Name required")
	// 		.min(2, "Last Name must be at least 2 characters"),
	// 	initialValue: "",
	// 	icon: <Person />,
	// 	required: true,
	// 	contactField: {
	// 		xs: 12,
	// 		sm: 12,
	// 		md: 6,
	// 		lg: 6,
	// 	},
	// },
	{
		key: "3",
		name: "time",
		label: "Time *",
		placeholder: "Enter Time",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Time Required"),
		type: "time",
		initialValue: "",
		icon: <AccessTimeFilled />,
		required: true,
	},
	{
		key: "1",
		name: "medicineName",
		label: "Medicine Name *",
		placeholder: "Enter Medicine Name",
		styleContact: "rounded-lg",
		type: "text",
		validationSchema: Yup.string().required("Medicine name required"),
		initialValue: "",
		icon: <Bloodtype />,
		required: true,
	},
	{
		key: "4",
		name: "qty",
		label: "Qty *",
		placeholder: "Enter Medicine Quantity *",
		type: "number",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Medicine Quantity required"),
		initialValue: "",
		icon: <Info />,
		required: true,
	},
	{
		key: "5",
		name: "totalPrice",
		label: "Total Price *",
		placeholder: "Enter Total Price",
		type: "number",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Total price required"),
		initialValue: "",
		// icon: <Info />,
		required: true,
		// multiline: true,
		// rows: 2,
	},
];
export default MedicineSchemas;
