import {
	Category,
	Create,
	Info,
	Badge,
	Description,
	CurrencyRupee,
	Percent,
} from "@mui/icons-material";
import * as Yup from "yup";

const PaymentProcedureSchemas = [
	{
		key: "1",
		// placeholder: 'Enter your name',
		name: "code",
		label: "Code *",
		placeholder: "Enter Code",
		styleContact: "rounded-xl overflow-hidden bg-white",
		type: "text",
		validationSchema: Yup.string().required("Code Required"),
		initialValue: "",
		icon: <Create />,
		required: true,
	},
	{
		key: "2",
		// placeholder: 'Enter your name',
		name: "itemName",
		label: "Payment Item Name *",
		placeholder: "Enter Payment Item Name",
		styleContact: "rounded-xl overflow-hidden bg-white",
		type: "text",
		validationSchema: Yup.string().required("Payment Item Name Required"),
		initialValue: "",
		icon: <Badge />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "3",
		// placeholder: 'Enter your name',
		name: "description",
		label: "Description *",
		placeholder: "Enter Description",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Description is Required"),
		type: "text",
		initialValue: "",
		multiline: true,
		rows: 2,
		icon: <Description />,
		required: true,
		contactField: {
			xs: 12,
			sm: 12,
			md: 6,
			lg: 6,
		},
	},
	{
		key: "4",
		// placeholder: 'Enter your name',
		name: "categoryPrice",
		label: "Category Price *",
		placeholder: "Enter Category Price",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Category Price is required"),
		type: "text",
		initialValue: "",
		icon: <CurrencyRupee />,
		required: true,
	},
	{
		key: "5",
		// placeholder: 'Enter your name',
		name: "commission",
		label: "Doctor's Commission Rate ( % ) *",
		placeholder: "Enter Doctor's Commission Rate",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required(
			"Doctor's commission rate is required"
		),
		type: "text",
		initialValue: "",
		icon: <Percent />,
		required: true,
	},
	{
		key: "6",
		// placeholder: 'Enter your name',
		name: "type",
		label: "Type *",
		placeholder: "Enter Type",
		styleContact: "rounded-xl overflow-hidden bg-white ",
		validationSchema: Yup.string().required("Type is required"),
		type: "text",
		initialValue: "",
		icon: <Create />,
		required: true,
	},
];
export default PaymentProcedureSchemas;
