import {
	DateRange,
	HealthAndSafety,
	Info,
	LocationCity,
	MedicationLiquid,
	Vaccines,
} from "@mui/icons-material";
import * as Yup from "yup";

const PrescriptionSchemas = [
	{
		key: "1",
		name: "selectPatient",
		label: "Select Patient",
		placeholder: "Select Patient",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Select Patient"),

		initialValue: "",
		// icon: <HealthAndSafety />,
		required: true,
	},
	{
		key: "2",
		name: "drug",
		label: "Select Drug *",
		placeholder: "Drug",
		// type: "text",
		styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Drug name is required"),
		initialValue: "",
		// icon: <Vaccines />,
		required: true,
	},
	{
		key: "3",
		// placeholder: 'Enter your email',
		name: "strength",
		label: "Strength *",
		placeholder: "Enter Drug Strength",
		styleContact: "rounded-lg",
		// type: "text",
		validationSchema: Yup.string().required("Drug Strength is required"),
		initialValue: "",
		// icon: <MedicationLiquid />,
		required: true,
	},
	// {
	// 	key: "4",
	// 	// placeholder: 'Enter your email',
	// 	name: "frequency",
	// 	label: "Frequency *",
	// 	placeholder: "",
	// 	styleContact: "rounded-lg",
	// 	type: "text",
	// 	validationSchema: Yup.string().required("Frequency is required"),
	// 	initialValue: "",
	// 	// icon: <Vaccines />,
	// 	required: true,
	// },
	{
		key: "4",
		name: "instruction",
		label: "Instruction *",
		validationSchema: Yup.string().required("Instruction is required"),
		styleContact: "rounded-lg",
		// type: "text",
		initialValue: "",
		placeholder: "Enter Instruction",
		// icon: <Info />,
		required: true,
	},
	{
		key: "5",
		name: "time",
		label: "Time *",
		validationSchema: Yup.string().required("Time is required"),
		styleContact: "rounded-lg",
		// type: "text",
		initialValue: "",
		placeholder: "Enter Instruction",
		// icon: <Info />,
		required: true,
	},
	{
		key: "5",
		// placeholder: 'Enter your phone number',
		name: "duration",
		label: "Duration *",
		placeholder: "Enter Duration",
		styleContact: "rounded-lg",
		type: "number",
		validationSchema: Yup.string().required("Duration is required"),
		initialValue: "",
		// icon: <LocalPhone />,
		required: true,
	},

	{
		key: "5",
		name: "note",
		label: "Prescription Notes *",
		placeholder: "Enter Prescription Notes",
		type: "text",
		// styleContact: "rounded-lg",
		validationSchema: Yup.string().required("Prescription Note is required"),
		initialValue: "",
		required: true,
		multiline: true,
		rows: 2,
	},

	// {
	// 	key: "14",
	// 	name: "countryCode",
	// 	label: "countryDetails",
	// 	placeholder: "Country Code",
	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().optional(),

	// 	initialValue: "",
	// 	icon: <LocalPhone />,
	// 	required: true,
	// },

	// {
	// 	key: "6",
	// 	name: "city",
	// 	label: "City *",
	// 	validationSchema: Yup.string().required("City is required"),
	// 	styleContact: "rounded-lg",
	// 	initialValue: "",
	// 	placeholder: "City",
	// 	icon: <LocationCity />,
	// 	required: true,
	// },
	// {
	// 	key: "8",
	// 	name: "street",
	// 	label: "Street *",
	// 	placeholder: "Street",

	// 	styleContact: "rounded-lg",
	// 	validationSchema: Yup.string().required("Street is required"),
	// 	icon: <Traffic />,
	// 	initialValue: "",
	// 	required: true,
	// },
	// {
	// 	key: "9",
	// 	name: "zipCode",
	// 	type: "text",
	// 	placeholder: "ZipCode",
	// 	styleContact: "rounded-lg",
	// 	label: "ZipCode*",
	// 	validationSchema: Yup.string().required("ZipCode is required"),
	// 	initialValue: "",
	// 	icon: <PushPin />,
	// 	required: true,
	// },
	// {
	// 	key: "10.2",
	// 	name: "state",
	// 	type: "text",
	// 	placeholder: "State",
	// 	styleContact: "rounded-lg",
	// 	label: "State",
	// 	validationSchema: Yup.string().optional(),
	// 	initialValue: "",
	// 	icon: <AccessAlarm />,
	// 	required: true,
	// },
	// {
	// 	key: "10",
	// 	name: "latitude",
	// 	type: "text",
	// 	placeholder: "Latitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Latitude*",
	// 	validationSchema: Yup.string().required("Latitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
	// {
	// 	key: "11",
	// 	name: "longitude",
	// 	type: "text",
	// 	placeholder: "Longitude",
	// 	styleContact: "rounded-lg",
	// 	label: "Longitude*",
	// 	validationSchema: Yup.string().required("Longitude is required"),
	// 	initialValue: "",
	// 	icon: <AddLocationAlt />,
	// 	required: true,
	// },
	// {
	// 	key: "11",
	// 	name: "timing",
	// 	type: "text",
	// 	placeholder: "Store Timing",
	// 	styleContact: "rounded-lg",
	// 	label: "Store Opening Hours*",
	// 	validationSchema: Yup.string().required("Store Timing is required"),
	// 	initialValue: "",
	// 	row: 2,
	// 	multiline: true,
	// 	// icon: <AddLocationAlt />,
	// 	required: true,
	// },
];
export default PrescriptionSchemas;
